/// Embeds the generated T3 wires for the device: reads
/// tools/dossier/e2e_payloads/ (produced by gen_e2e_payloads.dart, sizes
/// pinned to phase-5) plus the chat dictionary, and emits
/// integration_test/support/e2e_payloads.dart as base64 constants — the
/// device has no repo filesystem, so the wires ride inside the test binary.
///
/// Run from apps/reference_app:  dart run tool/embed_e2e_payloads.dart
library;

import 'dart:convert';
import 'dart:io';

const _repo = '../..';
const _dir = '$_repo/tools/dossier/e2e_payloads';

void main() {
  final tsv = File('$_dir/payloads.tsv').readAsLinesSync();
  if (tsv.length < 6) {
    throw StateError('payloads.tsv incomplete — run gen_e2e_payloads first');
  }
  // provenance: the text row's source names the corpus msg id
  final textSource = tsv.firstWhere((l) => l.startsWith('text_29b.bin'));
  final textId =
      int.parse(RegExp(r'msg id=(\d+)').firstMatch(textSource)!.group(1)!);
  final textMsg = File('$_repo/tools/phase5/corpus/chat_corpus_200.jsonl')
      .readAsLinesSync()
      .map((l) => jsonDecode(l) as Map<String, dynamic>)
      .firstWhere((m) => m['id'] == textId);
  final page = jsonDecode(
          File('$_repo/tools/phase5/corpus/news_ref_page.json')
              .readAsStringSync())
      as Map<String, Object?>;

  String b64(String name) =>
      base64Encode(File('$_dir/$name').readAsBytesSync());
  final dictB64 = base64Encode(
      File('$_repo/packages/messaging/assets/zstd_chat.dict')
          .readAsBytesSync());

  final gen = StringBuffer()
    ..writeln('// GENERATED by tool/embed_e2e_payloads.dart — do not edit.')
    ..writeln('// Sources: tools/dossier/e2e_payloads/payloads.tsv (sha256')
    ..writeln('// per item, sizes pinned to phase-5 h3_results.tsv).')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln('library;')
    ..writeln()
    ..writeln("const String kTextWireB64 = '${b64('text_29b.bin')}';")
    ..writeln('const int kTextMsgId = $textId;')
    ..writeln('const String kTextExpected = ${jsonEncode(textMsg['text'])};')
    ..writeln("const String kNewsWireB64 = '${b64('news_1160b.bin')}';")
    ..writeln("const String kVoiceWireB64 = '${b64('voice_879b.bin')}';")
    ..writeln("const String kPhotoWireB64 = '${b64('photo_2682b.avif')}';")
    ..writeln("const String kVideoWireB64 = '${b64('video_5926b.bin')}';")
    ..writeln("const String kZstdChatDictB64 = '$dictB64';")
    ..writeln('const String kNewsExpectedJson =')
    ..writeln('    ${jsonEncode(jsonEncode(page))};');
  File('integration_test/support/e2e_payloads.dart')
      .writeAsStringSync(gen.toString());
  stdout.writeln('integration_test/support/e2e_payloads.dart written');
}
