/// Emits the shared wire vectors both implementations are checked against.
///
/// The Dart client and the JavaScript relay both parse the same records,
/// and until now each knew the layout only from its own code. That is
/// exactly how two implementations of one format drift: nothing fails
/// until a real deployment mixes an old reader with a new writer.
///
/// These vectors are the format written down. Both sides check themselves
/// against the same file, so a layout change that only lands on one side
/// fails immediately, in both languages, with the same message.
///
/// Regenerate with:
///
///     dart run tool/emit_conformance_vectors.dart
///
/// and commit the result. Regenerating is a deliberate act: if the bytes
/// change, the wire format changed, and that is the thing worth noticing.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:broadcast/broadcast.dart';

/// A key pair fixed by seed, so the vectors are byte-stable across runs.
///
/// Test material only — it names nothing and protects nothing.
final Uint8List _rootSeed = Uint8List.fromList(
  List.generate(32, (i) => (i * 7 + 1) & 0xFF),
);
final Uint8List _publishingSeed = Uint8List.fromList(
  List.generate(32, (i) => (i * 11 + 5) & 0xFF),
);

String _hex(Uint8List bytes) => hexEncode(bytes);

Future<void> main() async {
  final root = await CryptographyBroadcastSigner.fromSeed(_rootSeed);
  final publishing = await CryptographyBroadcastSigner.fromSeed(
    _publishingSeed,
  );
  final authorId = authorIdFor(root.publicKey);

  final notBefore = DateTime.utc(2026, 1, 1);
  final certificate = await PublishingKeyCertificate.issue(
    rootSigner: root,
    publishingKey: publishing.publicKey,
    notBefore: notBefore,
    notAfter: notBefore.add(const Duration(days: 7)),
  );

  final textOnly = await BroadcastDescriptor.sign(
    signer: publishing,
    authorId: authorId,
    seq: 0,
    publishedAt: DateTime.utc(2026, 1, 1, 12),
    prev: zeroHash,
    layers: {
      LayerFlag.text: contentHash(Uint8List.fromList([1, 2, 3])),
    },
  );

  final everyLayer = await BroadcastDescriptor.sign(
    signer: publishing,
    authorId: authorId,
    seq: 41,
    publishedAt: DateTime.utc(2026, 1, 2, 9, 30),
    prev: textOnly.id,
    layers: {
      LayerFlag.text: contentHash(Uint8List.fromList([1])),
      LayerFlag.still: contentHash(Uint8List.fromList([2])),
      LayerFlag.voice: contentHash(Uint8List.fromList([3])),
      LayerFlag.mediaList: contentHash(Uint8List.fromList([4])),
    },
  );

  final retraction = await BroadcastDescriptor.sign(
    signer: publishing,
    authorId: authorId,
    seq: 42,
    publishedAt: DateTime.utc(2026, 1, 2, 10),
    prev: everyLayer.id,
    layers: {
      LayerFlag.text: contentHash(Uint8List.fromList([5])),
    },
    retracts: textOnly.id,
  );

  final quotableText = Uint8List.fromList(
    'the bridge is closed; do not go north'.codeUnits,
  );
  final quotable = await BroadcastDescriptor.sign(
    signer: publishing,
    authorId: authorId,
    seq: 7,
    publishedAt: DateTime.utc(2026, 1, 1, 18),
    prev: textOnly.id,
    layers: {LayerFlag.text: contentHash(quotableText)},
  );
  final evidence = PostEvidence.build(
    rootPublicKey: root.publicKey,
    certificate: certificate,
    descriptor: quotable,
    text: quotableText,
  );

  final directory = await RelayDirectory.issue(
    rootSigner: root,
    origins: [
      Uri.parse('https://relay-one.example'),
      Uri.parse('https://relay-two.example:8443'),
    ],
    seq: 3,
    notAfter: DateTime.utc(2026, 6, 1),
  );

  final bootstrap = BootstrapCode(
    host: 'relay-one.example',
    rootPublicKey: root.publicKey,
  );

  final vectors = {
    'note':
        'Shared wire vectors for the broadcast format. Generated by '
        'packages/broadcast/tool/emit_conformance_vectors.dart. Both the '
        'Dart client and the JavaScript relay verify themselves against '
        'this file; a change here is a change to the wire format.',
    'version': 1,
    'keys': {
      'rootSeedHex': _hex(_rootSeed),
      'rootPublicKeyHex': _hex(root.publicKey),
      'publishingSeedHex': _hex(_publishingSeed),
      'publishingPublicKeyHex': _hex(publishing.publicKey),
      'authorIdHex': _hex(authorId),
    },
    'certificate': {
      'notBeforeSeconds': notBefore.millisecondsSinceEpoch ~/ 1000,
      'notAfterSeconds':
          notBefore.add(const Duration(days: 7)).millisecondsSinceEpoch ~/ 1000,
      'encodedHex': _hex(certificate.encoded),
      'byteLength': certificate.encoded.length,
    },
    'descriptors': [
      {
        'name': 'text only, genesis',
        'seq': 0,
        'flags': textOnly.flags,
        'publishedAtSeconds':
            textOnly.publishedAt.millisecondsSinceEpoch ~/ 1000,
        'encodedHex': _hex(textOnly.encoded),
        'idHex': _hex(textOnly.id),
        'byteLength': textOnly.encoded.length,
      },
      {
        'name': 'every layer, linked',
        'seq': 41,
        'flags': everyLayer.flags,
        'publishedAtSeconds':
            everyLayer.publishedAt.millisecondsSinceEpoch ~/ 1000,
        'prevHex': _hex(everyLayer.prev),
        'encodedHex': _hex(everyLayer.encoded),
        'idHex': _hex(everyLayer.id),
        'byteLength': everyLayer.encoded.length,
      },
      {
        'name': 'a retraction, withdrawing the genesis post',
        'seq': 42,
        'flags': retraction.flags,
        'publishedAtSeconds':
            retraction.publishedAt.millisecondsSinceEpoch ~/ 1000,
        'prevHex': _hex(retraction.prev),
        'retractsHex': _hex(retraction.retracts!),
        'encodedHex': _hex(retraction.encoded),
        'idHex': _hex(retraction.id),
        'byteLength': retraction.encoded.length,
      },
    ],
    'postEvidence': {
      'note':
          'A self-contained bundle the offline web verifier checks. Both '
          'the Dart implementation and tools/web_verifier read these bytes.',
      'text': String.fromCharCodes(quotableText),
      'seq': 7,
      'publishedAtSeconds': quotable.publishedAt.millisecondsSinceEpoch ~/ 1000,
      'encodedHex': _hex(evidence),
      'base64': base64.encode(evidence),
      'byteLength': evidence.length,
    },
    'relayDirectory': {
      'seq': 3,
      'origins': [for (final o in directory.origins) o.toString()],
      'encodedHex': _hex(directory.encoded),
    },
    'bootstrapCode': {
      'host': bootstrap.host,
      'text': bootstrap.encode(),
      'encodedHex': _hex(bootstrap.encodeBytes()),
    },
    'addresses': {
      'descriptorPath': DescriptorAddress(authorId: authorId, seq: 41).path,
      'objectPath': ObjectAddress(
        contentHash(Uint8List.fromList([1, 2, 3])),
      ).path,
      'immutableCacheControl': immutableCacheControl,
    },
    'authHeader': {
      'name': broadcastAuthHeader,
      'value': BroadcastCredentials.of(root.publicKey, certificate).headerValue,
    },
  };

  final file = File('test/conformance/wire_vectors.json');
  await file.parent.create(recursive: true);
  await file.writeAsString(
    '${const JsonEncoder.withIndent('  ').convert(vectors)}\n',
  );
  stdout.writeln('wrote ${file.path}');
}
